### ISSUE TITLE
Keyboard tab switching not working

### ISSUE THREAD

**Issue by oliver-dungey** [juho-p/fatty#14]
Thanks for the great little package. It all compiled and ran fine first time but the keyboard tab navigation isn't working for me - if I click the tab tops with the mouse it switches fine, if I use CTRL+SHIFT+ARROW the tab tops change order but the window contents remain the same (might be swapping the wrong thing).

**Comment by juho-p** [comment]
Try pressing SHIFT+ARROW.

CTRL+SHIFT+ARROW is for moving tabs around.

Best solution would probably have the keys being configurable in the options window, so people could really easily to also see what the keys actually are. But I'm pretty sure I'm too lazy for such features.

**Comment by oliver-dungey** [comment]
@juho-p sorry, my bad, can't read properly. Thanks for showing me the light. I really like the keys, nice and simple and obvious and works on Mac/Windows/remote-desktop without any problems
