### ISSUE TITLE
Current tab highlight

### ISSUE THREAD

**Issue by oliver-dungey** [juho-p/fatty#15]
Feature suggestion - it would be great if the currently active tab was highlighted clearly, inverse video (i.e. black on green goes to green on black) or bold/font-change might work nicely.

**Comment by juho-p** [comment]
I like the idea of bold font for active tab.

**Comment by juho-p** [comment]
Bold font for active tab implemented in 187f984bc12ccd268bd6558c0ca3a3d9420d0429

**Comment by oliver-dungey** [comment]
@juho-p much appreciated feature, thanks
