### ISSUE TITLE
Closing tab on maximize window shrink window vertically

### ISSUE THREAD

**Issue by pawel-jakubowski** [juho-p/fatty#16]
If I have only two tabs and close one maximized window will shrink.

Before:
![image](https://cloud.githubusercontent.com/assets/9104400/15667336/10137902-2716-11e6-8125-2ee5aaec51fd.png)

After:
![image](https://cloud.githubusercontent.com/assets/9104400/15667365/33e44e6a-2716-11e6-87dc-3ddab023fc26.png)

**Comment by juho-p** [comment]
Same as https://github.com/juho-p/fatty/issues/9
