### ISSUE TITLE
Rename Tabs

### ISSUE THREAD

**Issue by parkour86** [juho-p/fatty#17]
I'd like to request the ability to rename tabs with ctrl+shift+r. Is this a planned feature or is there a way I can add it myself?

**Comment by juho-p** [comment]
I have not planned such feature, but I'm not against it either. You can implement it if you wish, I'll merge it whenever I have the time to do so.

**Comment by parkour86** [comment]
I would love to implement it but I don't know where to start or how to do it. Maybe someone else can look into it.

**Comment by ph1999** [comment]
Until then,   you can setup an alias in .bashrc 
``` bash
function set-title(){
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1=${ORIG}${TITLE}
}

# Then type the title you want
set-title NEW-TITLE
```

**Comment by parkour86** [comment]
That code works perfect. I took what you provided and modified it a bit. I added a hotkey (Alt+w); when pressed will bring up an input box asking for the new title. Then sets the title. 

I'm no longer running fatty as I have moved over to Ubuntu but this code is still needed in my day to day work. Thanks ph1999.

```bash
function set-title(){
  ANS=$(whiptail --title "Set Title" --inputbox "Enter New Title" 0 0 3>&1 1>&2 2>&3)
  respose=$?

  case $respose in
    0)
      if [[ -z "$ORIG" ]]; then
        ORIG=$PS1
      fi
      TITLE="\[\e]2;$ANS\a\]"
      PS1=${ORIG}${TITLE}
      ;;
    1)
      echo "Cancel pressed." 
      ;;
    255)
      echo "[ESC] key pressed."
  esac
}

bind '"\ew":"set-title\n"'
```

**Comment by juho-p** [comment]
Closing since this can "easily" be solved in shell as explained in above comments.
