### ISSUE TITLE
Vim in Fatty, Symbol rendering issues: ✓✫↔↗♂♛金☺✔✖☑☌✉∅♪♫

### ISSUE THREAD

**Issue by ryanerwin** [juho-p/fatty#18]
Attached are two screenshots running Vim, one directly under mintty, the other via fatty.
When using cat or zsh to echo the symbol directly to the console in fatty, the symbol is rendered properly, yet when inside of Vim (and presumably other interactive commands) the symbols above and presumably other symbols are not rendered correctly.

Meanwhile, the symbols are rendered properly when running via mintty, with the same minttyrc and vimrc.

![fatty-mintty](https://cloud.githubusercontent.com/assets/2156415/15998959/e0d4d6d6-3174-11e6-9928-3b9ee8fb4101.png)

**Comment by juho-p** [comment]
Could you provide an example file that shows this problem?

**Comment by juho-p** [comment]
Just tried this out and those symbols work well on my vim with bot mintty and fatty. Do you have any idea what kind of configuration causes this to happen to you?

**Comment by ryanerwin** [comment]
@juho-p,

I think this was just a cygwin bug of some sort... After rebooting, I was no longer able to replicate the problem. Very strange. Sorry, I'm still getting used to the move over to Windows, often forget that even in 2016 step 1 of debugging is still **reboot**...
