### ISSUE TITLE
Font boldness

### ISSUE THREAD

**Issue by nrclark** [juho-p/fatty#2]
I just cloned and built commit-tag 7fc5832. It looks great! I think I found a bug - it looks like FaTTY ignores the 'BoldAsFont' setting. Changing the option in the Fatty's preference window has no effect. Changing it in the config file has no effect either. It seems like BoldAsFont is always-on.

**Comment by nrclark** [comment]
Update: I did some poking around in the source code. It looks like the issue has to do with line 162 of wintext.c. Should that be instead be: `bold_mode = cfg.bold_as_font ? BOLD_FONT : BOLD_NONE;`?

**Comment by juho-p** [comment]
It seems to me that you are correct. Mintty changed it from SHADOW to NONE in commit 44e83137, but for me it makes more sense to have it as BOLD_NONE, so lets try that.
