### ISSUE TITLE
d2d2 should be included and linked with its real name (lowercase)

### ISSUE THREAD

**Issue by janflyborg** [juho-p/fatty#20]
Hi,

I am runnning Windows (and Cygwin) in case sensitive mode. That means that the names D2d1.h and d2d1.h does not refer to the same file in my file system.

Fatty includes and D2d1.h and links with -lD2d2 when it should use d2d1.h1 and -ld1d2. 

Had to change this to be able to build and it won't affect you who are running Windows case insentive, so could you please look into changing this?

Cheers
    //Jan Flyborg

**Comment by juho-p** [comment]
Thanks, I didn't notice that myself. It should be fixed now, by 2eb0532af21de970ae9dbc285dde65da230749aa

I don't have my Cygwin in case sensitive mode, so if it still doesn't work, just comment here so it can be fixed.

**Comment by janflyborg** [comment]
That sounds good. Thanks for this. I will try to build tomorrow at work and will report back if the problem is still there.
