### ISSUE TITLE
Shortcuts for changing tabs don't work

### ISSUE THREAD

**Issue by tuetschek** [juho-p/fatty#23]
The Ctrl+(Shift+)Tab shortcuts for changing tabs don't seem to work in the current version. Also, is it possible to change tabs with Ctrl+PgUp/Dn? Otherwise the app is very nice, thanks :-)!

**Comment by juho-p** [comment]
See https://github.com/juho-p/fatty/issues/14

Ideally, there should be configuration for settings the keyboard shortcut, but at the moment that is too big task (for me) to implement, since I don't want to spent a lot of time for this project.
