### ISSUE TITLE
Command to launch with multiple tabs

### ISSUE THREAD

**Issue by DinkydauSet** [juho-p/fatty#27]
The page https://github.com/juho-p/fatty says that "You can spawn multiple tabs." but I can't figure out how. The example command given launches fatty with only one tab and doesn't seem to be modifiable to make multiple tabs at once.

I would like to use one command to launch fatty with 3 tabs with a different program running in each of them. If it requires calling a script that's okay.

**Comment by DinkydauSet** [comment]
I found out how. I would swear I already tried this before asking but it's as simple as `fatty -b "commands for tab 1" -b "commands for tab 2" ...`

**Comment by juho-p** [comment]
A valid question though... I clarified the README, hopefully it's more clear now.
