### ISSUE TITLE
Make - issue

### ISSUE THREAD

**Issue by ottobricks** [juho-p/fatty#34]
I ran into an snprintf error in child.c while runnign make.
All required packages are correctly installed.
I hope you can help me out on this one
![image](https://user-images.githubusercontent.com/22245994/40874770-e5074f98-6649-11e8-9888-de5f0b1649c8.png)

**Comment by juho-p** [comment]
Thanks for reporting this. This happens in new gcc versions. The problem is now fixed. You should try pulling newest version and compiling again.

I also removed -Werror flag from Makefile for now so it shouldn't break so easily in the future when gcc adds more warnings.
