### ISSUE TITLE
Path as tab name

### ISSUE THREAD

**Issue by Thx61** [juho-p/fatty#36]
In README screenshot I see that tab name indicate your path, but in my situation all tab name is '/bin/bash', is that normal, or can I fix it?

Enjoy using FaTTY btw, nice work!

**Comment by juho-p** [comment]
How do you run fatty? Shell should normally be able to set the tab title, but it won't if you use something like tmux.

**Comment by Thx61** [comment]
Maybe the reason is my customed PS1, after realizing my shell title is always '/bin/bash' too, I add '\e]0;\w\a' to the head of my customed PS1 in .bashrc.

And it work, PERFECT!  Thanks!

see https://superuser.com/questions/362227/how-to-change-the-title-of-the-mintty-window

**Comment by juho-p** [comment]
Very nice that you got it working! Thanks for posting the real reason, since it could help others as well. (PS1 is kinda obvious here, but it sure didn't come to my mind yesterday.)
