### ISSUE TITLE
git pull/git fetch takes forever on fatty

### ISSUE THREAD

**Issue by nghia-le** [juho-p/fatty#37]
I installed Cygwin and then fatty as in the readme file here: https://github.com/juho-p/fatty

When I cd to my project and git pull or git fetch, it just hang on forever. 
I tried "git checkout <branch>" or "git status" it worked.
So I think there must be something wrong with the credentials. 

All the above commands work with Cygwin normally.

**Comment by nghia-le** [comment]
Apparently Cygwin retrieves ssh keys in cygwin64/home/(user)/.ssh (path A) while fatty does it in C:/Users/(user)/.ssh (path B). I copied the .ssh folder from path A to path B and it worked. 
So what I'm now asking is, is there a ways to force fatty to retrieves SSH key from path A instead of path B, since it's running the core of Cygwin? @juho-p

**Comment by juho-p** [comment]
This seems to be duplicate to https://github.com/juho-p/fatty/issues/35 (which might also be duplicate, but I'd have to investigate more)
