### ISSUE TITLE
multiple definition

### ISSUE THREAD

**Issue by tanshujiang** [juho-p/fatty#39]
when I follow the instructions and make the files, it turns out so many 'multiple definition of xxxx' errors

**Comment by juho-p** [comment]
You're right. I tried to build with newest gcc in cygwin, and it didn't work at all (I hadn't build fatty in so many months so I wasn't aware). Seems there were some linking issues that older versions of the GCC tolerated but not anymore.

Should be fixed now in 7fb71bbd3f7e573d40552897f39ea72f06a03536
