### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by uahim** [juho-p/fatty#7]
I'm aware this may not be fatty's fault, but as I am a newbie and it doesn't compile, I thought I'll ask here - I also did a little websearch for this error, to no avail.

I did as required, installed all the packages described in fatty readme. after starting make, this is what happens after a minute or so:

```
g++ -DTARGET=i686-pc-cygwin -DNDEBUG -Wall -Wextra -std=gnu++11 -Os -c childxx.cc -o build/childxx.o -MMD -MT build/childxx.o
In file included from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/ext/string_conversions.h:41:0,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/bits/basic_string.h:5251,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/string:52,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/stdexcept:39,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/array:38,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/tuple:39,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/functional:55,
                 from /usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/memory:79,
                 from win.hh:18,
                 from childxx.cc:1:
/usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/cstdlib:126:11: error: ‘::at_quick_exit’ has not been declared
   using ::at_quick_exit;
           ^
/usr/lib/gcc/i686-pc-cygwin/5.3.0/include/c++/cstdlib:149:11: error: ‘::quick_exit’ has not been declared
   using ::quick_exit;
           ^
Makefile:45: recipe for target 'build/childxx.o' failed
make[1]: *** [build/childxx.o] Error 1
make[1]: Leaving directory '/c/~/fatty/src'
Makefile:2: recipe for target 'exe' failed
make: *** [exe] Error 2
```

if anyone has any idea, it would be of great help. thanks.

**Comment by juho-p** [comment]
I just build fatty with fresh install of Cygwin to try this out (32 bit version as that's what you seem to have) and it worked for me.

It's hard to tell what's wrong in your case. You seem to have up to date gcc and the compilation error indicates a problem in the standard C++ library, which is weird to me.

Only suggestion that comes to my mind is to try to update your cygwin packages. Also try to reinstall g++ (run the setup*.exe again, in package selection, find g++ and click it until it says "reinstall")

**Comment by uahim** [comment]
@juho-p thanks, updating/reinstalling packages to most recent versions - and also fixing some dependencies - helped indeed.

maybe you should add to readme that fatty will only work on Windows versions starting with Vista, because it relies on Direct2D not available in previous versions of that OS (didn't want to open an extra issue for that).

once again, thanks for the hint.

**Comment by iakat** [comment]
Worth noting XP was supported until 8/4/2014 and should not be used anywhere; so not really an issue,
