### ISSUE TITLE
Tab Bar Separator

### ISSUE THREAD

**Issue by j5shi** [juho-p/fatty#8]
I extended the tab height by

``` c
  g_render_tab_height = win_tab_height() + 5;
```

and then I noticed there's a vertical bar which is shorter than tab height inbetween two tabs, do you know how to get rid of it?

``` c
+----------------------------------------------+
|     tab1            |       tab2             |
+----------------------------------------------+
                      ^
                      |
                  a solid short line

```

**Comment by juho-p** [comment]
You'd better change value 18 at line 212 at tabheight() function.

**Comment by j5shi** [comment]
Thanks, it works :dancers:
